/* Patch esclusiva demo-esatta. Nessun redesign. */
(function(){
 const photos=['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=500&q=75','https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=500&q=75','https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=500&q=75','https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=500&q=75','https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=500&q=75','https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=500&q=75'];
 const svg=k=>{const p={trophy:'<path d="M6 3h12v3c0 4-2.5 7-6 7S6 10 6 6V3Zm0 2H3v2c0 3 2 5 5 5M18 5h3v2c0 3-2 5-5 5M12 13v4m-4 3h8m-6-3h4"/>',medal:'<circle cx="12" cy="9" r="4"/><path d="m9 13-2 8 5-3 5 3-2-8M8 3 6 7m10-4 2 4"/>',star:'<path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/>',people:'<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2"/><path d="M3 20c0-4 2.5-6 6-6s6 2 6 6m0-5c3 0 5 1.5 5 5"/>'};return `<svg class="fs-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${p[k]||p.star}</svg>`};
 function paintPhotos(){document.querySelectorAll('.cards .photo').forEach((e,i)=>e.style.setProperty('--demo-photo',`url("${photos[i%photos.length]}")`))}
 function fitMapBox(){const mapEl=document.getElementById('map'),wrap=document.querySelector('.mapwrap');if(!mapEl||!wrap)return;const h=mapEl.getBoundingClientRect().height||430;wrap.style.minHeight='0';wrap.style.height=h+'px';if(window.map&&typeof window.map.invalidateSize==='function')setTimeout(()=>window.map.invalidateSize(),30)}
 function enhanceComparison(){const m=document.getElementById('listing-modal'),h=m&&m.querySelector('h2');if(!h||!/Confronta gli alloggi/i.test(h.textContent))return;const bar=document.getElementById('compare-bar');if(bar)bar.style.setProperty('display','none','important');const map={'Più vicino':'medal','Top distanza':'star','Meno concorrenza':'people','TOP costo':'trophy'};h.closest('section')?.querySelectorAll('span').forEach(s=>{const raw=s.textContent.replace(/[□★🏆]/g,'').trim();for(const [label,kind] of Object.entries(map)){if(raw.includes(label)&&!s.querySelector('.fs-icon')){s.innerHTML=svg(kind)+' '+label;s.classList.add('fs-eval');break}}});const grid=h.closest('section')?.querySelector('div[style*="grid-template-columns"]');if(grid){grid.classList.add('fs-compare-grid');[...grid.children].forEach((c,i)=>{if(i<3)c.classList.add('fs-compare-head');else if(i%3===0)c.classList.add('fs-compare-label')})}}
 const originalRender=window.render;if(typeof originalRender==='function')window.render=function(){const r=originalRender.apply(this,arguments);requestAnimationFrame(()=>{paintPhotos();fitMapBox()});return r};
 const originalOpen=window.openListing;if(typeof originalOpen==='function')window.openListing=function(){const r=originalOpen.apply(this,arguments);requestAnimationFrame(()=>{const p=document.querySelector('#listing-modal .photo');if(p){const i=Math.max(0,(window.listings||[]).findIndex(x=>x.id===arguments[0]));p.style.setProperty('--demo-photo',`url("${photos[i%photos.length]}")`)}});return r};
 document.addEventListener('click',function(e){const btn=e.target.closest('#compare-bar button');if(btn&&!btn.disabled){setTimeout(enhanceComparison,0);setTimeout(enhanceComparison,50)}const close=e.target.closest('#listing-modal button');if(close&&close.textContent.trim()==='×'){const bar=document.getElementById('compare-bar');if(bar)bar.style.removeProperty('display')}},true);
 document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{localStorage.removeItem('fuorisede-favourites');if(window.favourites&&typeof window.favourites.clear==='function')window.favourites.clear();document.querySelectorAll('.fav').forEach(b=>b.textContent='♡');paintPhotos();fitMapBox()},350));window.addEventListener('resize',fitMapBox);
})();