// FUORISEDE shared listing alert request flow.
// This UI intentionally does not claim that monitoring is active until a backend/feed exists.
(function(){
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function listingById(id){return (typeof state!=='undefined'&&state.items||[]).find(function(x){return String(x.id)===String(id)||String(x.externalId)===String(id)})}
  function install(){
    if(typeof state==='undefined'||typeof toggleListingAlert!=='function')return false;
    toggleListingAlert=function(id){
      const x=listingById(id);if(!x)return;
      document.getElementById('fs-alert-modal')?.remove();
      const ref=x.externalId||x.id;
      const modal=document.createElement('div');modal.id='fs-alert-modal';modal.className='fs-alert-overlay';
      modal.innerHTML=`<div class="fs-alert-card" role="dialog" aria-modal="true" aria-labelledby="fs-alert-title"><button class="fs-alert-close" type="button" aria-label="Chiudi">×</button><div class="eyebrow">FUORISEDE · AGGIORNAMENTI ALLOGGIO</div><h2 id="fs-alert-title">Avvisami sugli aggiornamenti</h2><p class="fs-alert-listing">${esc(x.title||'Alloggio')}<br><small>Riferimento ${esc(ref)}</small></p><p class="fs-alert-copy">Lascia la tua email per richiedere aggiornamenti su disponibilità, prezzo, spese e altre modifiche importanti di questa scheda.</p><form><label>Email<input name="email" type="email" autocomplete="email" required></label><p class="fs-alert-note">In questa fase la richiesta viene inviata a FUORISEDE. L’avviso automatico sarà attivato quando il monitoraggio periodico della fonte sarà operativo.</p><p class="fs-alert-privacy"><a href="/privacy.html" target="_blank" rel="noopener">Privacy</a></p><button class="fs-alert-submit" type="submit">Richiedi l’avviso</button></form></div>`;
      document.body.appendChild(modal);
      const close=function(){modal.remove()};modal.querySelector('.fs-alert-close').onclick=close;modal.addEventListener('click',function(e){if(e.target===modal)close()});modal.querySelector('input').focus();
      modal.querySelector('form').addEventListener('submit',function(e){e.preventDefault();const fd=new FormData(e.currentTarget);const subject=`FUORISEDE · Richiesta avviso alloggio ${ref}`;const body=[`Alloggio: ${x.title||''}`,`Riferimento: ${ref}`,`Città: ${x.city||''}`,`Email: ${fd.get('email')||''}`,'','Richiesta aggiornamenti raccolta tramite FUORISEDE.'].join('\n');location.href=`mailto:info@fuori-sede.it?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;modal.querySelector('.fs-alert-card').innerHTML='<div class="fs-alert-success"><b>Richiesta preparata ✓</b><p>Si apre il tuo programma di posta con il messaggio già compilato per FUORISEDE. L’avviso non viene indicato come attivo finché il monitoraggio automatico non è operativo.</p><button type="button" onclick="document.getElementById(\'fs-alert-modal\').remove()">Chiudi</button></div>'});
    };
    if(!document.getElementById('fs-alert-style')){const style=document.createElement('style');style.id='fs-alert-style';style.textContent='.fs-alert-overlay{position:fixed;inset:0;z-index:10000;background:#17171599;display:grid;place-items:center;padding:18px}.fs-alert-card{position:relative;width:min(520px,100%);max-height:calc(100vh - 36px);overflow:auto;background:#fff;border-radius:22px;padding:25px;box-shadow:0 22px 70px #0005}.fs-alert-card h2{margin:6px 34px 8px 0;font-size:25px}.fs-alert-close{position:absolute;right:14px;top:12px;border:0;background:transparent;font-size:30px;cursor:pointer}.fs-alert-listing{background:#f5f5f2;border-radius:13px;padding:11px 13px}.fs-alert-copy{font-size:13px;line-height:1.5}.fs-alert-card label{display:block;margin:12px 0;font-size:12px;font-weight:850}.fs-alert-card input{display:block;width:100%;margin-top:5px;padding:11px 12px;border:1px solid var(--line,#ddd);border-radius:11px;background:#fff;font:inherit}.fs-alert-note,.fs-alert-privacy{font-size:11px;line-height:1.45;color:var(--muted,#6f6b67)}.fs-alert-submit,.fs-alert-success button{width:100%;border:1px solid #171715;border-radius:999px;padding:12px 16px;background:#171715;color:#fff;font-weight:900;cursor:pointer}.fs-alert-success{text-align:center;padding:18px 4px}.fs-alert-success b{font-size:21px}.fs-alert-success p{line-height:1.5;color:var(--muted,#6f6b67)}@media(max-width:600px){.fs-alert-overlay{padding:18px}.fs-alert-card{width:min(340px,calc(100vw - 36px));max-height:calc(100dvh - 36px);padding:14px;border-radius:16px}.fs-alert-card .eyebrow{font-size:8px}.fs-alert-card h2{font-size:17px;line-height:1.15;margin:3px 30px 6px 0}.fs-alert-close{right:10px;top:7px;font-size:25px}.fs-alert-copy{font-size:11px;line-height:1.35;margin:8px 0}.fs-alert-listing{font-size:11px;padding:7px 9px;margin:7px 0}.fs-alert-card label{font-size:10px;margin:7px 0}.fs-alert-card input{font-size:16px;padding:7px 9px}.fs-alert-note,.fs-alert-privacy{font-size:9px;line-height:1.3;margin:7px 0}.fs-alert-submit{padding:8px 12px;font-size:11px}}';document.head.appendChild(style)}
    return true;
  }
  if(!install()){let tries=0,t=setInterval(function(){if(install()||++tries>100)clearInterval(t)},50)}
})();