const state={items:[],selected:new Set(),favs:new Set(),neededFrom:"",sort:"date",detail:null,view:"list",compareOpen:false,maxPrice:"",quick:new Set(),moreFilters:false};
const euro=n=>n==null?"Da verificare":new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
const fmtDate=s=>{if(!s)return null;const d=new Date(`${s}T12:00:00`);return new Intl.DateTimeFormat("it-IT",{day:"numeric",month:"short",year:"numeric"}).format(d)};
const availabilityText=x=>x.availability?.availableLabel||fmtDate(x.availability?.availableFrom)||"Da verificare";
const statusText=x=>({confirmed:"Confermata",to_reconfirm:"Da riconfermare",unavailable:"Non disponibile",unknown:"Da verificare"}[x.availability?.status]||"Da verificare");
const costText=x=>x.realMonthlyCostStatus==="complete"?euro(x.realMonthlyCost):x.realMonthlyCostStatus==="minimum_known"?`${euro(x.realMonthlyCost)} + eventuali costi`:"Da verificare";
const distanceText=x=>x.campusReference?.distanceKm==null?"Percorso da calcolare":`${Number(x.campusReference.distanceKm).toLocaleString("it-IT",{minimumFractionDigits:2,maximumFractionDigits:2})} km`;
const campusShort=x=>(x.campusReference?.campusName||"Sede universitaria").split("·")[0].trim();
const features=x=>x.features||[]; const featureText=x=>features(x).join(' ').toLowerCase();
const contractText=x=>x.details?.contract||"Da verificare"; const utilitiesText=x=>x.details?.utilities||"Da verificare";
const confirmationText=x=>x.validation?.listingConfirmedAt?fmtDate(x.validation.listingConfirmedAt):x.availability?.confirmedAt?fmtDate(x.availability.confirmedAt):"Da verificare";
function compatibility(x){if(!state.neededFrom)return{rank:0,label:""};if(x.availability?.status==="unavailable")return{rank:3,label:"Non disponibile"};const a=x.availability?.availableFrom;if(!a)return{rank:2,label:"Verifica la data"};return a<=state.neededFrom?{rank:0,label:"✓ Compatibile con la tua data"}:{rank:1,label:`Solo dal ${availabilityText(x)}`}}
function matches(x){if(state.maxPrice&&Number(x.realMonthlyCost??x.price??Infinity)>Number(state.maxPrice))return false;const t=featureText(x);for(const q of state.quick){if(q==='wifi'&&!/wi.?fi|wifi/.test(t))return false;if(q==='lavatrice'&&!t.includes('lavatrice'))return false;if(q==='bagno'&&!/bagno/.test(t))return false;if(q==='arredato'&&!/arredat|ammobiliat/.test(t))return false}return true}
function sorted(){return [...state.items].filter(matches).sort((a,b)=>state.sort==="price"?(a.realMonthlyCost??Infinity)-(b.realMonthlyCost??Infinity):state.sort==="availability"?String(a.availability?.availableFrom||"9999").localeCompare(String(b.availability?.availableFrom||"9999")):compatibility(a).rank-compatibility(b).rank)}
function setNeededFrom(v){state.neededFrom=v;render()} function setSort(v){state.sort=v;render()} function setMaxPrice(v){state.maxPrice=v;render()} function toggleQuick(v){state.quick.has(v)?state.quick.delete(v):state.quick.add(v);render()} function toggleMore(){state.moreFilters=!state.moreFilters;render()} function clearFilters(){state.neededFrom='';state.maxPrice='';state.quick.clear();state.sort='date';render()} function setView(v){state.view=v;state.detail=null;state.compareOpen=false;render();scrollTo({top:0,behavior:'smooth'})} function toggleFav(id){state.favs.has(id)?state.favs.delete(id):state.favs.add(id);render()} function toggleCompare(id,on){const k=Number(id);on?state.selected.add(k):state.selected.delete(k);if(state.selected.size>3){state.selected.delete(k);alert('Puoi confrontare fino a 3 alloggi.')}if(state.selected.size<2)state.compareOpen=false;render()} function openComparison(){if(state.selected.size<2)return;state.compareOpen=true;state.detail=null;render();scrollTo({top:0,behavior:'smooth'})} function closeComparison(){state.compareOpen=false;render()} function clearComparison(){state.selected.clear();state.compareOpen=false;render()} function openDetail(id){state.detail=Number(id);state.compareOpen=false;render();scrollTo({top:0,behavior:'smooth'})} function closeDetail(){state.detail=null;render()}
function nav(){return `<nav class="v3nav"><button class="${state.view==='list'?'active':''}" onclick="setView('list')">⌂ Alloggi <b>${sorted().length}</b></button><button class="${state.view==='map'?'active':''}" onclick="setView('map')">⌖ Mappa</button><button class="${state.view==='favs'?'active':''}" onclick="setView('favs')">♡ Preferiti <b>${state.favs.size}</b></button></nav>`}
function filters(){const chips=[['wifi','Wi-Fi'],['lavatrice','Lavatrice'],['bagno','Bagno privato'],['arredato','Arredato']];const active=state.neededFrom||state.maxPrice||state.quick.size;return `<section class="panel"><div class="filtertitle"><h2>Trova il tuo posto</h2>${active?`<button class="resetfilters" onclick="clearFilters()">Azzera</button>`:''}</div><label>Mi serve dal<input type="date" value="${state.neededFrom}" onchange="setNeededFrom(this.value)"></label><div class="quickchips">${chips.map(([v,l])=>`<button class="filterchip ${state.quick.has(v)?'on':''}" onclick="toggleQuick('${v}')">${l}</button>`).join('')}<button class="filterchip more ${state.moreFilters?'on':''}" onclick="toggleMore()">${state.moreFilters?'− Meno':'+ Altri filtri'}</button></div>${state.moreFilters?`<div class="morefilterbox"><label>Budget massimo<select onchange="setMaxPrice(this.value)"><option value="">Qualsiasi</option><option value="350">Fino a €350</option><option value="450">Fino a €450</option><option value="600">Fino a €600</option></select></label><label>Mostrami prima<select onchange="setSort(this.value)"><option value="date">Adatti alla mia data</option><option value="price">Meno costosi</option><option value="availability">Disponibili prima</option></select></label></div>`:''}<div class="resultline"><b>${sorted().length}</b> alloggi autorizzati</div></section>`}
function compareDock(){const n=state.selected.size;if(!n)return'';return `<div class="comparedock"><span><b>${n}</b> selezionati</span>${n>=2?`<button onclick="openComparison()">Confronta ora</button>`:`<small>Scegline almeno un altro</small>`}</div>`}
function comparison(){const xs=state.items.filter(x=>state.selected.has(Number(x.id)));const rows=[['Canone',x=>euro(x.price)],['Costo reale',costText],['Disponibilità',availabilityText],['Spese / utenze',utilitiesText],['Contratto',contractText],['Dotazioni',x=>features(x).slice(0,4).join(', ')||'Da verificare']];return `<section class="compareview"><div class="comparehead"><button class="back" onclick="closeComparison()">← Torna agli alloggi</button><button class="clearcompare" onclick="clearComparison()">Azzera</button></div><h1>Confronta ciò che conta</h1><div class="comparetable">${rows.map(([label,fn])=>`<div class="comparerow"><div class="comparelabel">${label}</div><div class="comparevalues">${xs.map(x=>`<div><strong>${x.title}</strong><br>${fn(x)}</div>`).join('')}</div></div>`).join('')}</div></section>`}
function card(x){const c=compatibility(x),id=Number(x.id),fs=features(x).slice(0,3);return `<article class="card"><div class="cardbody"><div class="eyebrow">${x.city} · ${x.publication.source}</div><div class="favline"><div onclick="openDetail(${id})"><div class="title">${x.title}</div><div class="price">${euro(x.price)} <span>/ mese</span></div></div><button class="heart" onclick="toggleFav(${id})">${state.favs.has(id)?'♥':'♡'}</button></div><div><span class="badge">📅 ${availabilityText(x)}</span>${c.label?`<span class="badge warn">${c.label}</span>`:''}</div><div class="features">${fs.map(f=>`<span class="badge">${f}</span>`).join('')}</div><div class="cardactions"><button class="detailsbtn" onclick="openDetail(${id})">Scopri</button><label><input type="checkbox" ${state.selected.has(id)?'checked':''} onchange="toggleCompare('${id}',this.checked)"> Confronta</label></div></div></article>`}
function contactActions(x){const c=x.contactWorkflow;if(!c)return `<button class="secondaryaction" disabled>Contatto da integrare</button>`;if(c.type==='source_url')return `<a class="primaryaction" href="${c.url}" target="_blank" rel="noopener">${c.label}</a>`;if(c.type==='phone')return `<a class="primaryaction" href="tel:${c.phone.replace(/\s/g,'')}">${c.label}</a>`;return ''}
function detailView(x){const id=Number(x.id);return `${nav()}<section class="detail"><button class="back" onclick="closeDetail()">← Tutti gli alloggi</button><div class="detailbody"><div class="eyebrow">${x.city} · fonte ${x.publication.source}</div><h1>${x.title}</h1><div class="price">${euro(x.price)} <span>/ mese</span></div><div><span class="badge">📅 ${availabilityText(x)}</span><span class="badge">📍 ${x.address}</span></div><h2>In breve</h2><div>${features(x).map(f=>`<span class="badge">${f}</span>`).join('')}</div><h2>Costi e disponibilità</h2><div class="row"><span>Costo reale / mese</span><strong>${costText(x)}</strong></div><div class="row"><span>Disponibilità</span><strong>${statusText(x)}</strong></div><div class="row"><span>Spese / utenze</span><strong>${utilitiesText(x)}</strong></div><div class="row"><span>Contratto</span><strong>${contractText(x)}</strong></div><div class="row"><span>Deposito</span><strong>${x.details?.deposit||'Da verificare'}</strong></div><h2>Trasparenza</h2><div class="trustbox"><div class="trustitem"><span>✓ Pubblicazione</span><strong>Autorizzata</strong></div><div class="trustitem"><span>✓ Ultima verifica</span><strong>${confirmationText(x)}</strong></div><div class="trustitem"><span>Fonte</span><strong>${x.publication.source}</strong></div><p>Le informazioni mancanti restano indicate come “Da verificare”.</p></div><h2>Dove si trova</h2><div class="mapbox">📍 ${x.address}<br><b>${distanceText(x)} da ${campusShort(x)}</b></div><div class="actions">${contactActions(x)}${x.publication.sourceUrl?`<a class="secondaryaction" href="${x.publication.sourceUrl}" target="_blank" rel="noopener">Fonte ufficiale</a>`:''}</div><button class="compareaction" onclick="toggleCompare('${id}',${!state.selected.has(id)})">${state.selected.has(id)?'✓ Nel confronto':'⇄ Confronta'}</button></div></section>${compareDock()}`}
function render(){const root=document.getElementById('v3-root');if(state.compareOpen){root.innerHTML=nav()+comparison();return}if(state.detail){const x=state.items.find(i=>Number(i.id)===state.detail);root.innerHTML=x?detailView(x):'';return}if(state.view==='map'){root.innerHTML=nav()+filters()+`<section class="empty"><h2>Mappa in preparazione</h2><p>I quattro alloggi sono pubblicati, ma i percorsi verso le sedi universitarie saranno attivati solo dopo la verifica delle coordinate.</p></section>`+compareDock();return}const xs=state.view==='favs'?sorted().filter(x=>state.favs.has(Number(x.id))):sorted();root.innerHTML=nav()+filters()+(xs.length?xs.map(card).join(''):`<section class="empty"><h2>Nessun alloggio con questi filtri</h2><button class="detailsbtn" onclick="clearFilters()">Azzera filtri</button></section>`)+compareDock()}
async function init(){try{const r=await fetch('../data/listings-operativa.json',{cache:'no-store'});if(!r.ok)throw new Error(r.status);state.items=(await r.json()).filter(x=>x.publication?.authorized===true);render()}catch(e){document.getElementById('v3-root').innerHTML='<section class="panel"><b>Dataset operativo non disponibile.</b></section>';console.error(e)}}init();