const state={items:[],selected:new Set(),favs:new Set(),neededFrom:"",sort:"date"};
const euro=n=>n==null?"Da verificare":new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
const fmtDate=s=>{if(!s)return null;const d=new Date(`${s}T12:00:00`);return new Intl.DateTimeFormat("it-IT",{day:"numeric",month:"long",year:"numeric"}).format(d)};
const availabilityText=x=>x.availability?.availableLabel||fmtDate(x.availability?.availableFrom)||"Da verificare";
const statusText=x=>({confirmed:"Confermata",to_reconfirm:"Da riconfermare",unavailable:"Non disponibile",unknown:"Da riconfermare"}[x.availability?.status]||"Da riconfermare");
const costText=x=>x.realMonthlyCostStatus==="complete"?euro(x.realMonthlyCost):x.realMonthlyCostStatus==="minimum_known"?`da ${euro(x.realMonthlyCost)}`:"Da verificare";
const distanceText=x=>x.campusReference?.distanceKm==null?"Distanza da calcolare":`${Number(x.campusReference.distanceKm).toLocaleString("it-IT",{minimumFractionDigits:2,maximumFractionDigits:2})} km`;
const campusShort=x=>(x.campusReference?.campusName||"Sede da scegliere").split("·")[0].trim();
const featureChips=x=>{const known=(x.features||[]).filter(f=>!/dati mancanti/i.test(f));if(known.length)return known;return ["Wi‑Fi da verificare","Lavatrice da verificare","Cucina da verificare","Bagno da verificare"]};
function compatibility(x){if(!state.neededFrom)return{rank:0,label:""};if(x.availability?.status==="unavailable")return{rank:3,label:"Non disponibile"};const a=x.availability?.availableFrom;if(!a)return{rank:2,label:"Data da verificare"};return a<=state.neededFrom?{rank:0,label:"Compatibile con la tua data"}:{rank:1,label:`Solo dal ${availabilityText(x)}`}}
function sorted(){return [...state.items].sort((a,b)=>state.sort==="price"?(a.realMonthlyCost??Infinity)-(b.realMonthlyCost??Infinity):state.sort==="distance"?(a.campusReference?.distanceKm??Infinity)-(b.campusReference?.distanceKm??Infinity):state.sort==="availability"?String(a.availability?.availableFrom||"9999").localeCompare(String(b.availability?.availableFrom||"9999")):compatibility(a).rank-compatibility(b).rank)}
function setNeededFrom(v){state.neededFrom=v;render()}function setSort(v){state.sort=v;render()}function toggleFav(id){state.favs.has(id)?state.favs.delete(id):state.favs.add(id);render()}function toggleCompare(id,on){const k=Number(id);on?state.selected.add(k):state.selected.delete(k);if(state.selected.size>3){state.selected.delete(k);alert("Puoi confrontare fino a 3 alloggi.")}render()}
function comparison(){const xs=state.items.filter(x=>state.selected.has(Number(x.id)));if(xs.length<2)return"";const row=(l,f)=>`<div class="row"><span>${l}</span><strong>${xs.map(f).join(" · ")}</strong></div>`;return `<section class="panel"><h2 class="section-title">Confronta gli alloggi</h2>${row("Canone",x=>euro(x.price))}${row("Costo mensile noto",costText)}${row("Distanza",distanceText)}${row("Disponibile dal",availabilityText)}${state.neededFrom?row("Per la tua data",x=>compatibility(x).label):""}${row("Caratteristiche",x=>(x.features||[]).join(", ")||"da verificare")}${row("Spese",x=>x.details?.utilities||"da verificare")}${row("Contratto",x=>x.details?.contract||"da verificare")}</section>`}
function render(){const root=document.getElementById("v2-root");root.innerHTML=`<section class="panel"><h2 class="section-title">Trova il tuo alloggio</h2><label class="note">Mi serve dal<input type="date" value="${state.neededFrom}" onchange="setNeededFrom(this.value)"></label><label class="note" style="display:block;margin-top:10px">Ordina per<select onchange="setSort(this.value)"><option value="date" ${state.sort==="date"?"selected":""}>Compatibilità con la mia data</option><option value="price" ${state.sort==="price"?"selected":""}>Costo</option><option value="distance" ${state.sort==="distance"?"selected":""}>Distanza dalla sede</option><option value="availability" ${state.sort==="availability"?"selected":""}>Prima disponibilità</option></select></label><p class="note">La sede è un riferimento per confrontare distanze e tempi, non un confine: nessun alloggio viene escluso perché si trova in un'altra zona.</p></section>`+sorted().map(x=>{const c=compatibility(x),id=Number(x.id);return `<article class="card"><div class="photo"></div><div class="cardbody"><div class="eyebrow">${x.city} · riferimento: ${campusShort(x)}</div><div class="favline"><div><div class="title">${x.title}</div><div class="price">${euro(x.price)} <span class="muted">canone / mese</span></div></div><button class="heart" onclick="toggleFav(${id})" title="Preferiti">${state.favs.has(id)?"♥":"♡"}</button></div><div><span class="badge">📅 ${availabilityText(x)}</span><span class="badge">📍 ${distanceText(x)} dalla sede*</span>${c.label?`<span class="badge ${c.rank===0?"":"warn"}">${c.label}</span>`:""}</div><div style="margin:8px 0 3px">${featureChips(x).map(f=>`<span class="badge ${/verificare/i.test(f)?"warn":""}">${f}</span>`).join("")}</div><div class="row"><span>Costo mensile noto</span><strong>${costText(x)}</strong></div><div class="row"><span>Disponibilità</span><strong class="${x.availability?.status==="confirmed"?"good":"unknown"}">${statusText(x)}</strong></div><div class="row"><span>Spese / utenze</span><strong class="${x.validation?.utilitiesDeclared?"good":"unknown"}">${x.details?.utilities||"Da verificare"}</strong></div><div class="row"><span>Contratto</span><strong class="${x.validation?.contractDeclared?"good":"unknown"}">${x.details?.contract||"Da verificare"}</strong></div><div class="comparebox"><label><input type="checkbox" style="width:auto" ${state.selected.has(id)?"checked":""} onchange="toggleCompare('${id}',this.checked)"> Confronta</label></div><p class="note" style="margin:10px 0 0">* Distanza geografica indicativa rispetto alla sede scelta. I tempi reali saranno mostrati solo con routing attendibile.</p></div></article>`}).join("")+comparison()}
async function init(){try{const r=await fetch("../data/listings-v2-pilot.json",{cache:"no-store"});if(!r.ok)throw new Error(r.status);state.items=await r.json();render()}catch(e){document.getElementById("v2-root").innerHTML='<section class="panel"><b>Dataset V2 non disponibile.</b></section>';console.error(e)}}init();