const state={items:[],selected:new Set(),neededFrom:"",sort:"date"};
const euro=n=>n==null?"Da verificare":new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
const fmtDate=s=>{if(!s)return null;const d=new Date(`${s}T12:00:00`);return new Intl.DateTimeFormat("it-IT",{day:"numeric",month:"long",year:"numeric"}).format(d)};
const availabilityText=x=>x.availability?.availableLabel||fmtDate(x.availability?.availableFrom)||"Da verificare";
const statusText=x=>({confirmed:"Disponibilità confermata",to_reconfirm:"Disponibilità da riconfermare",unavailable:"Non disponibile",unknown:"Disponibilità da riconfermare"}[x.availability?.status]||"Disponibilità da riconfermare");
const costText=x=>x.realMonthlyCostStatus==="complete"?euro(x.realMonthlyCost):x.realMonthlyCostStatus==="minimum_known"?`da ${euro(x.realMonthlyCost)}`:"Da verificare";
const distanceText=x=>x.campusReference?.distanceKm==null?"Distanza da calcolare":`${Number(x.campusReference.distanceKm).toLocaleString("it-IT",{minimumFractionDigits:2,maximumFractionDigits:2})} km dalla sede*`;
function score(x){const v=x.validation||{};return [v.contactProvided,v.priceDeclared,v.expensesDeclared,v.contractDeclared,v.depositDeclared,v.utilitiesDeclared].filter(Boolean).length}
function compatibility(x){if(!state.neededFrom)return{rank:0,label:""};if(x.availability?.status==="unavailable")return{rank:3,label:"Non disponibile"};const a=x.availability?.availableFrom;if(!a)return{rank:2,label:"Data da verificare"};return a<=state.neededFrom?{rank:0,label:"Disponibile per la tua data"}:{rank:1,label:`Disponibile dal ${availabilityText(x)}`}}
function sorted(){return [...state.items].sort((a,b)=>state.sort==="price"?(a.realMonthlyCost??Infinity)-(b.realMonthlyCost??Infinity):state.sort==="distance"?(a.campusReference?.distanceKm??Infinity)-(b.campusReference?.distanceKm??Infinity):state.sort==="availability"?String(a.availability?.availableFrom||"9999").localeCompare(String(b.availability?.availableFrom||"9999")):compatibility(a).rank-compatibility(b).rank)}
function setNeededFrom(v){state.neededFrom=v;render()}function setSort(v){state.sort=v;render()}function toggleCompare(id,on){const k=Number(id);on?state.selected.add(k):state.selected.delete(k);if(state.selected.size>3){state.selected.delete(k);alert("Puoi confrontare fino a 3 alloggi.")}render()}
function comparison(){const xs=state.items.filter(x=>state.selected.has(Number(x.id)));if(xs.length<2)return"";const row=(l,f)=>`<div class="row"><span>${l}</span><strong>${xs.map(f).join(" · ")}</strong></div>`;return `<section class="panel"><h2 class="section-title">Confronta i tuoi preferiti</h2>${row("Costo mensile",costText)}${row("Distanza dalla sede",distanceText)}${row("Disponibile dal",availabilityText)}${state.neededFrom?row("Per la tua data",x=>compatibility(x).label):""}${row("Spese",x=>x.validation?.expensesDeclared?"indicate":"da verificare")}${row("Contratto",x=>x.validation?.contractDeclared?"indicato":"da verificare")}</section>`}
function render(){const root=document.getElementById("v2-root");root.innerHTML=`<section class="panel"><h2 class="section-title">Trova il tuo alloggio</h2><label class="note">Mi serve dal<input type="date" value="${state.neededFrom}" onchange="setNeededFrom(this.value)"></label><label class="note" style="display:block;margin-top:10px">Ordina per<select onchange="setSort(this.value)"><option value="date" ${state.sort==="date"?"selected":""}>Compatibilità con la mia data</option><option value="price" ${state.sort==="price"?"selected":""}>Costo</option><option value="distance" ${state.sort==="distance"?"selected":""}>Distanza dalla sede</option><option value="availability" ${state.sort==="availability"?"selected":""}>Prima disponibilità</option></select></label><p class="note">Scegli in base a ciò che conta per te: data, costo e distanza dalla sede. Nessuna zona viene esclusa automaticamente.</p></section>`+sorted().map(x=>{const c=compatibility(x);return `<section class="card"><div class="eyebrow">${x.city}</div><div class="title">${x.title}</div><div class="price">${euro(x.price)} <span class="muted">/ mese</span></div><div><span class="badge">${availabilityText(x)}</span><span class="badge">${distanceText(x)}</span>${c.label?`<span class="badge ${c.rank===0?"":"warn"}">${c.label}</span>`:""}</div><div class="row"><span>Costo mensile</span><strong>${costText(x)}</strong></div><div class="row"><span>Disponibilità</span><strong>${statusText(x)}</strong></div><div class="row"><span>Spese</span><strong class="${x.validation?.expensesDeclared?"good":"unknown"}">${x.validation?.expensesDeclared?"Indicate":"Da verificare"}</strong></div><div class="row"><span>Contratto</span><strong class="${x.validation?.contractDeclared?"good":"unknown"}">${x.validation?.contractDeclared?"Indicato":"Da verificare"}</strong></div><div class="row"><span>Sede scelta</span><strong>${x.campusReference?.campusName||"Da scegliere"}</strong></div><label class="note" style="display:flex;gap:8px;align-items:center;margin-top:12px"><input type="checkbox" style="width:auto" ${state.selected.has(Number(x.id))?"checked":""} onchange="toggleCompare('${x.id}',this.checked)"> ♡ Aggiungi ai preferiti e confronta</label><p class="note" style="margin-top:10px">* Distanza geografica indicativa; il tempo di percorrenza sarà mostrato solo quando disponibile da routing reale.</p></section>`}).join("")+comparison()}
async function init(){try{const r=await fetch("../data/listings-v2-pilot.json",{cache:"no-store"});if(!r.ok)throw new Error(r.status);state.items=await r.json();render()}catch(e){document.getElementById("v2-root").innerHTML='<section class="panel"><b>Dataset V2 non disponibile.</b></section>';console.error(e)}}init();