const state={items:[],selected:new Set(),favs:new Set(),neededFrom:"",sort:"date",detail:null};
const euro=n=>n==null?"Da verificare":new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
const fmtDate=s=>{if(!s)return null;const d=new Date(`${s}T12:00:00`);return new Intl.DateTimeFormat("it-IT",{day:"numeric",month:"long",year:"numeric"}).format(d)};
const availabilityText=x=>x.availability?.availableLabel||fmtDate(x.availability?.availableFrom)||"Da verificare";
const statusText=x=>({confirmed:"Confermata",to_reconfirm:"Da riconfermare",unavailable:"Non disponibile",unknown:"Da riconfermare"}[x.availability?.status]||"Da riconfermare");
const costText=x=>x.realMonthlyCostStatus==="complete"?euro(x.realMonthlyCost):x.realMonthlyCostStatus==="minimum_known"?euro(x.realMonthlyCost):"Da verificare";
const costLabel=x=>x.realMonthlyCostStatus==="complete"?"Costo mensile":"Costo mensile minimo noto";
const distanceText=x=>x.campusReference?.distanceKm==null?"Distanza da calcolare":`${Number(x.campusReference.distanceKm).toLocaleString("it-IT",{minimumFractionDigits:2,maximumFractionDigits:2})} km`;
const campusShort=x=>(x.campusReference?.campusName||"Sede da scegliere").split("·")[0].trim();
const features=x=>(x.features||[]).filter(f=>!/dati mancanti/i.test(f));
function compatibility(x){if(!state.neededFrom)return{rank:0,label:""};if(x.availability?.status==="unavailable")return{rank:3,label:"Non disponibile"};const a=x.availability?.availableFrom;if(!a)return{rank:2,label:"Data da verificare"};return a<=state.neededFrom?{rank:0,label:"Compatibile con la tua data"}:{rank:1,label:`Solo dal ${availabilityText(x)}`}}
function sorted(){return [...state.items].sort((a,b)=>state.sort==="price"?(a.realMonthlyCost??Infinity)-(b.realMonthlyCost??Infinity):state.sort==="distance"?(a.campusReference?.distanceKm??Infinity)-(b.campusReference?.distanceKm??Infinity):state.sort==="availability"?String(a.availability?.availableFrom||"9999").localeCompare(String(b.availability?.availableFrom||"9999")):compatibility(a).rank-compatibility(b).rank)}
function setNeededFrom(v){state.neededFrom=v;render()}function setSort(v){state.sort=v;render()}function toggleFav(id){state.favs.has(id)?state.favs.delete(id):state.favs.add(id);render()}function toggleCompare(id,on){const k=Number(id);on?state.selected.add(k):state.selected.delete(k);if(state.selected.size>3){state.selected.delete(k);alert("Puoi confrontare fino a 3 alloggi.")}render()}function openDetail(id){state.detail=Number(id);render();window.scrollTo({top:0,behavior:"smooth"})}function closeDetail(){state.detail=null;render()}
function unavailableAction(msg){alert(msg)}
function comparison(){const xs=state.items.filter(x=>state.selected.has(Number(x.id)));if(xs.length<2)return"";const row=(l,f)=>`<div class="row"><span>${l}</span><strong>${xs.map(f).join(" · ")}</strong></div>`;return `<section class="panel"><h2 class="section-title">Confronta gli alloggi</h2>${row("Canone",x=>euro(x.price))}${row("Costo mensile",costText)}${row("Distanza",distanceText)}${row("Disponibile dal",availabilityText)}${state.neededFrom?row("Per la tua data",x=>compatibility(x).label):""}${row("Caratteristiche",x=>features(x).join(", ")||"da verificare")}</section>`}
function detailView(x){const id=Number(x.id);return `<section class="detail"><button class="back" onclick="closeDetail()">← Torna agli alloggi</button><div class="detailphoto">Anteprima foto alloggio</div><div class="detailbody"><div class="eyebrow">${x.city} · riferimento: ${campusShort(x)}</div><div class="favline"><div><h1 class="detailtitle">${x.title}</h1><div class="price">${euro(x.price)} <span class="muted">canone / mese</span></div></div><button class="heart" onclick="toggleFav(${id})">${state.favs.has(id)?"♥":"♡"}</button></div><div><span class="badge">📅 ${availabilityText(x)}</span><span class="badge">📍 ${distanceText(x)} dalla sede*</span></div><h2 class="section-title detailsection">Caratteristiche</h2><div>${(features(x).length?features(x):["Dotazioni da verificare"]).map(f=>`<span class="badge">${f}</span>`).join("")}</div><h2 class="section-title detailsection">Costi e disponibilità</h2><div class="row"><span>${costLabel(x)}</span><strong>${costText(x)}</strong></div><div class="row"><span>Disponibilità</span><strong class="unknown">${statusText(x)}</strong></div><div class="row"><span>Spese / utenze</span><strong>${x.details?.utilities||"Da verificare"}</strong></div><div class="row"><span>Contratto</span><strong>${x.details?.contract||"Da verificare"}</strong></div><div class="row"><span>Deposito</span><strong>${x.details?.deposit||"Da verificare"}</strong></div><h2 class="section-title detailsection">Posizione</h2><div class="mapbox">📍 ${x.address}<br><b>${distanceText(x)} dalla sede ${campusShort(x)}</b><br><span class="note">Spazio riservato alla mini-mappa. I tempi reali saranno mostrati solo con routing attendibile.</span></div><h2 class="section-title detailsection">Azioni</h2><div class="actions"><button class="primaryaction" onclick="unavailableAction('Candidatura non attiva nella preview: questa scheda pilota non è autorizzata alla pubblicazione.')">Candidati</button><button class="secondaryaction" onclick="unavailableAction('Contatto non disponibile nella preview finché la scheda non è autorizzata.')">Contatta</button><button class="secondaryaction" onclick="unavailableAction('Link all’annuncio originale non ancora disponibile per questa scheda pilota.')">Annuncio originale</button><button class="secondaryaction" onclick="unavailableAction('Segnalazione disponibile quando la scheda sarà pubblicata.')">Segnala</button></div><label class="comparebox"><input type="checkbox" style="width:auto" ${state.selected.has(id)?"checked":""} onchange="toggleCompare('${id}',this.checked)"> Aggiungi al confronto</label></div></section>`}
function render(){const root=document.getElementById("v2-root");if(state.detail){const x=state.items.find(i=>Number(i.id)===state.detail);root.innerHTML=x?detailView(x):"";return}root.innerHTML=`<section class="panel"><h2 class="section-title">Trova il tuo alloggio</h2><label class="note">Mi serve dal<input type="date" value="${state.neededFrom}" onchange="setNeededFrom(this.value)"></label><label class="note" style="display:block;margin-top:10px">Ordina per<select onchange="setSort(this.value)"><option value="date" ${state.sort==="date"?"selected":""}>Compatibilità con la mia data</option><option value="price" ${state.sort==="price"?"selected":""}>Costo</option><option value="distance" ${state.sort==="distance"?"selected":""}>Distanza dalla sede</option><option value="availability" ${state.sort==="availability"?"selected":""}>Prima disponibilità</option></select></label><p class="note">La sede è un riferimento per confrontare distanze e tempi, non un confine.</p></section>`+sorted().map(x=>{const c=compatibility(x),id=Number(x.id),fs=features(x).slice(0,3);return `<article class="card"><div class="photo" onclick="openDetail(${id})"></div><div class="cardbody"><div class="eyebrow">${x.city} · riferimento: ${campusShort(x)}</div><div class="favline"><div class="cardclick" onclick="openDetail(${id})"><div class="title">${x.title}</div><div class="price">${euro(x.price)} <span class="muted">canone / mese</span></div></div><button class="heart" onclick="toggleFav(${id})">${state.favs.has(id)?"♥":"♡"}</button></div><div><span class="badge">📅 ${availabilityText(x)}</span><span class="badge">📍 ${distanceText(x)} dalla sede</span>${c.label?`<span class="badge ${c.rank===0?"":"warn"}">${c.label}</span>`:""}</div>${fs.length?`<div class="features">${fs.map(f=>`<span class="badge">${f}</span>`).join("")}</div>`:""}<div class="cardactions"><button class="detailsbtn" onclick="openDetail(${id})">Vedi scheda</button><label class="comparebox"><input type="checkbox" style="width:auto" ${state.selected.has(id)?"checked":""} onchange="toggleCompare('${id}',this.checked)"> Confronta</label></div></div></article>`}).join("")+comparison()}
async function init(){try{const r=await fetch("../data/listings-v2-pilot.json",{cache:"no-store"});if(!r.ok)throw new Error(r.status);state.items=await r.json();render()}catch(e){document.getElementById("v2-root").innerHTML='<section class="panel"><b>Dataset V2 non disponibile.</b></section>';console.error(e)}}init();